apiVersion: v1
entries:
  woocommerce:
  - apiVersion: v2
    appVersion: "1.0"
    created: "2026-03-01T15:20:12.7956067+05:30"
    description: WooCommerce store provisioning chart
    digest: 98e828dbeb8b45275a1c786cf86f418e2d941584242a0aac17ff0a6bf0af7105
    name: woocommerce
    type: application
    urls:
    - woocommerce-0.1.0.tgz
    version: 0.1.0
generated: "2026-03-01T15:20:12.7945944+05:30"
