apiVersion: v1
entries:
  wordpress-e2e-setup:
  - apiVersion: v2
    appVersion: "1.0"
    created: "2026-03-02T12:31:32.5021715+05:30"
    description: Helm chart for automated end-to-end provisioning of WordPress WooCommerce
      stores on Kubernetes
    digest: 9bea256d8e90dba25f7605df66f1ce31f8c7bb3938761124f2a7aeb8d1690bf3
    name: wordpress-e2e-setup
    type: application
    urls:
    - wordpress-e2e-setup-0.1.1.tgz
    version: 0.1.1
generated: "2026-03-02T12:31:32.5003945+05:30"
